name: Deploy to AWS EC2

on:
  push:
    branches:
      - master # Trigger deployment on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to EC2 using password
        env:
          SSH_PASSWORD: ${{ secrets.EC2_SSH_PASSWORD }}
        run: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@47.237.87.59 << 'EOF'
            cd /var/www/hexcub_client

            echo "ðŸ› ï¸ Pulling latest code..."
            git pull origin master

            echo "ðŸ³ Building Docker containers..."
            docker-compose build

            echo "ðŸ”„ Restarting with docker-compose..."
            docker-compose down
            docker-compose up -d --remove-orphans

            echo "âœ… Deployment finished!"
          EOF
